In [2]:
import sqlite3
import pandas as pd

In [3]:
conn = sqlite3.connect('mi_base_de_datos.sqlite')

cursor = conn.cursor()

In [90]:
cursor.execute('''CREATE TABLE IF NOT EXISTS Parque_atracciones (
                    Nombre TEXT,
                    Direccion TEXT,
                    Ciudad TEXT,
                    Provincia TEXT,
                    Aforo INTEGER,
                    Codigo TEXT PRIMARY KEY
                )''')


# Crear la tabla Atracciones
# Eliminar la tabla existente si existe
cursor.execute('''DROP TABLE IF EXISTS Atracciones''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre TEXT,
                    Tipo TEXT,
                    Duracion INT,
                    Categoria_edad TEXT,
                    Longitud_Atraccion REAL,
                    Altura_Minima INTEGER,
                    Descripcion TEXT,  
                    codigo_atraccion TEXT,
                    codigo_parque TEXT)
                                        
                ''')



cursor.execute('''CREATE TABLE IF NOT EXISTS Zonas (
                    Codigo_Zona TEXT PRIMARY KEY,
                    Ambientacion TEXT,
                    Platos_Tipicos TEXT,
                    Espectaculos TEXT,
                    Descripcion
                    Horario TEXT,
                    Afluencia_Media INTEGER
                )''')


cursor.execute('''CREATE TABLE IF NOT EXISTS Alojamiento (
                    Nombre TEXT,
                    Precio REAL,
                    Categoria TEXT,
                    Servicios TEXT,
                    Ambientacion TEXT
                )''')

# Guardar los cambios y cerrar la conexión
#conn.commit()
#conn.close()
#cursor.close()

In [92]:
cursor.execute('''INSERT OR IGNORE INTO Parque_atracciones 
                  VALUES ('Port Aventura', 'Calle', 'Salou', 'Tarragona', 51000, '01')''')
cursor.execute('''INSERT OR IGNORE INTO Parque_atracciones 
                  VALUES ('parque2', 'Calle2', 'caspe', 'zaragoza', 5112312, '12312')''')
cursor.execute('''INSERT OR IGNORE INTO Parque_atracciones 
                  VALUES ('Terra Mitica', 'Partida del Moralet', 'Benidorm', 'Alicante', 10000, '03')''')
# PARQUE ATRACCIONES - WARNER BROSS  
cursor.execute('''INSERT OR IGNORE INTO Parque_atracciones 
                  VALUES ('Warner', 'Partida del Moralet, s/n' , 'Benidorm', 'Alicante', 1002300, '03')''')
# Atracciones 



#conn.commit()

In [93]:
# PARQUE ATRACCIONES - TERRA MITICA 

# Atracciones 

# Egipto 031
cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Puerto de Alejandria',
                    'Familiar',
                    2,
                    'Desconocido',
                    0.92,
                    'Disfruta de las vistas desde las naves Seker y Henu, que parten de la orilla egipcia con destino a Iberia. Una plácida travesía por el mar Mediterráneo en la que entrarás en contacto con los paisajes marítimos del parque y sus costas. Un paseo panorámico que bien puede servir como una primera toma de contacto con el Parque',
                    'A1',
                    '03', 
                    '031')''') 

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ('Cataratas del Nilo',
                    'Emocionante',
                    6,
                    30,
                    1.20,
                    'Deslízate por una montaña rusa de agua en los sarcófagos del Faraón. A ti no te embalsamarán, pero te aseguramos que saldrás empapado de esta atracción, especialmente si te sitúas al final del vehículo. Prepárate para sentir el vértigo en sus dos caídas, la primera desde casi 20 m, y la segunda, de espaldas desde 10 m',
                    'A2',
                    '03', 
                    '031')''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ("Akuatiti",
                    "Infantil",
                    3,
                    "Desconocido",
                    0.92,
                    "Los más pequeños también pueden disfrutar de un paseo por las cataratas del Nilo en sarcófagos biplazas. Pero tranquilos, para que los niños no se asusten, en esta atracción se han suprimido las caídas de su hermana mayor, y los giros no permiten salir tan empapado",
                    "A3",
                    '03', 
                    '031')''')
cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ("Infinito",
                    "Familiar",
                    6,
                    100,
                    0.92,
                    "Ofrece unas vistas privilegiadas de Terra Mítica, Benidorm y el Mediterráneo, mientras giras y subes",
                    "A4",
                    '03', 
                    '031')''')


# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "Cataratas del Nilo",
#                     Tipo "Emocionante",
#                     Edad_minima 6,
#                     Longitud_Atraccion 30,
#                     Altura_Minima 1.20,
#                     Descripcion "Deslízate por una montaña rusa de agua en los sarcófagos del Faraón. A ti no te embalsamarán, pero te aseguramos que saldrás empapado de esta atracción, especialmente si te sitúas al final del vehículo. Prepárate para sentir el vértigo en sus dos caídas, la primera desde casi 20 m, y la segunda, de espaldas desde 10 m"
#                     codigo_atraccion "A2",
#                     codigo_parque 03,
#                     codigo_zona 031,
#                     FOREIGN KEY (codigo_parque) REFERENCES Parque_atracciones(Codigo)''')

# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "Akuatiti",
#                     Tipo "Infantil",
#                     Edad_minima 3,
#                     Longitud_Atraccion "Desconocido",
#                     Altura_Minima 0.92,
#                     Descripcion "Los más pequeños también pueden disfrutar de un paseo por las cataratas del Nilo en sarcófagos biplazas. Pero tranquilos, para que los niños no se asusten, en esta atracción se han suprimido las caídas de su hermana mayor, y los giros no permiten salir tan empapado"
#                     codigo_atraccion "A3",
#                     codigo_parque 03,
#                     codigo_zona 031,
#                     ''')

# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "Infinito",
#                     Tipo "Familiar",
#                     Edad_minima 6,
#                     Longitud_Atraccion 100,
#                     Altura_Minima 0.92,
#                     Descripcion "Ofrece unas vistas privilegiadas de Terra Mítica, Benidorm y el Mediterráneo, mientras giras y subes"
#                     codigo_atraccion "A4",
#                     codigo_parque 03,
#                     codigo_zona 031,
#                     ''')

# Roma 032
"""
cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ("Tornado",
                    "Emocionante",
                    12,
                    80,
                    1.30,
                    "¿Te atreves a desafiar una imponente torre de 80 metros de altura de la que penden sillas voladoras y que giran sin cesar a distintas alturas e intensidades?"
                    "A13",
                    03,
                    032)''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ("Ayquesustus",
                    "Infantil",
                    5,
                    6,
                    0.92,
                    "No hay excusa para que los más pequeños disfruten de una caída libre como la del Vuelo del Fénix. Sus 6 metros de altura son suficientes para causar una emoción insuperable en los niños. Además, no pueden pasar por esta atracción sin hacerse una foto aprovechando su diseño, que incluye lanzas y cascos que parecen haberse escapado de las cabezas de los pequeños guerreros"
                    "A15",
                    03,
                    032) ''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ("Rotundus",
                    "Infantil",
                    3,
                    -,
                    0.92,
                    "Disfruta de las vistas a la plaza romana con esta noria infantil, ideal para toda la familia. Los vehículos con forma de pájaro elevarán suavemente a los niños por encima de la empalizada romana"
                    "A16",
                    03,
                    032)''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ("Inferno",
                    "Emocionante",
                    14,
                    -,
                    1.40,
                    "¿Te crees capaz de estar boca abajo, boca arriba, de lado, girar y sentir igual que una pelota volando a 60 km/h? ¿Eres así de lanzado? Tu te lo crees, pero nosotros no: ésta es tu oportunidad de demostrarlo. Menos hablar y más actuar..."
                    "A17",
                    03,
                    032)''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ("El vuelo del Fenix",
                    "Emocionante",
                    10,
                    54,
                    1.30,
                    "¿Estás preparado para experimentar una verdadera caída desde 54 metros de altura con una aceleración de 0.25g? en menos de 3 segundos, 100 km/h correrán por tus venas sin apenas poder respirar, lo que permite experimentar intensas sensaciones a los más osados. ¡Seguro que repites!"
                    "A18",
                    03,
                    032)''')



# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "Tornado",
#                     Tipo "Emocionante",
#                     Edad_minima 12,
#                     Longitud_Atraccion 80,
#                     Altura_Minima 1.30,
#                     Descripcion "¿Te atreves a desafiar una imponente torre de 80 metros de altura de la que penden sillas voladoras y que giran sin cesar a distintas alturas e intensidades?"
#                     codigo_atraccion A13,
#                     codigo_parque 03,
#                     codigo_zona 032,
#                     ''')

# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "Ayquesustus",
#                     Tipo "Infantil",
#                     Edad_minima 5,
#                     Longitud_Atraccion 6,
#                     Altura_Minima 0.92,
#                     Descripcion "No hay excusa para que los más pequeños disfruten de una caída libre como la del Vuelo del Fénix. Sus 6 metros de altura son suficientes para causar una emoción insuperable en los niños. Además, no pueden pasar por esta atracción sin hacerse una foto aprovechando su diseño, que incluye lanzas y cascos que parecen haberse escapado de las cabezas de los pequeños guerreros"
#                     codigo_atraccion A15,
#                     codigo_parque 03,
#                     codigo_zona 032,
#                     ''')

# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "Rotundus",
#                     Tipo "Infantil",
#                     Edad_minima 3,
#                     Longitud_Atraccion -,
#                     Altura_Minima 0.92,
#                     Descripcion "Disfruta de las vistas a la plaza romana con esta noria infantil, ideal para toda la familia. Los vehículos con forma de pájaro elevarán suavemente a los niños por encima de la empalizada romana"
#                     codigo_atraccion A16,
#                     codigo_parque 03,
#                     codigo_zona 032,
#                     ''')

# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "Inferno",
#                     Tipo "Emocionante",
#                     Edad_minima 14,
#                     Longitud_Atraccion -,
#                     Altura_Minima 1.40,
#                     Descripcion "¿Te crees capaz de estar boca abajo, boca arriba, de lado, girar y sentir igual que una pelota volando a 60 km/h? ¿Eres así de lanzado? Tu te lo crees, pero nosotros no: ésta es tu oportunidad de demostrarlo. Menos hablar y más actuar..."
#                     codigo_atraccion A17,
#                     codigo_parque 03,
#                     codigo_zona 032,
#                     ''')

# cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
#                     Nombre "El vuelo del Fenix",
#                     Tipo "Emocionante",
#                     Edad_minima 10,
#                     Longitud_Atraccion 54,
#                     Altura_Minima 1.30,
#                     Descripcion "¿Estás preparado para experimentar una verdadera caída desde 54 metros de altura con una aceleración de 0.25g? en menos de 3 segundos, 100 km/h correrán por tus venas sin apenas poder respirar, lo que permite experimentar intensas sensaciones a los más osados. ¡Seguro que repites!"
#                     codigo_atraccion A18,
#                     codigo_parque 03,
#                     codigo_zona 032,
#                     ''')

# Las islas 033
cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Mithos",
                    Tipo "Familiar",
                    Edad_minima 3,
                    Longitud_Atraccion 54,
                    Altura_Minima 0.92,
                    Descripcion "Un brillante carrusel que llama la atención por el día gracias a los espejos que pasean su reflejo por todas partes cuando gira y, por la noche, las bombillas de colores se encienden para dar al entorno el ambiente más alegre de Iberia"
                    codigo_atraccion A20,
                    codigo_parque 03,
                    codigo_zona 033,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "La colera de Aquiles",
                    Tipo "Emocionante",
                    Edad_minima 14,
                    Longitud_Atraccion -,
                    Altura_Minima 1.20,
                    Descripcion "Te elevas hacia el cielo mientras te balanceas a un lado y a otro, mientras giras y te inclinas hasta 120 grados. Mientras intentas saber si estás arriba o abajo, mientras decides si vas hacia la izquierda o hacia la derecha... piénsatelo mientras decides si subes o no"
                    codigo_atraccion A21,
                    codigo_parque 03,
                    codigo_zona 033,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Rapidos de Argos",
                    Tipo "Familiar",
                    Edad_minima 0,
                    Longitud_Atraccion -,
                    Altura_Minima 1.20,
                    Descripcion "Cuando aprieta el calor en el Parque sienta de maravilla un recorrido en barca siguiendo la ruta marítima en busca del Vellocino de Oro. Los viajeros, montados en una nave circular con neumáticos que los hacen rebotar y girar por todo el curso del río, se ven zarandeados por la corriente"
                    codigo_atraccion A22,
                    codigo_parque 03,
                    codigo_zona 033,
                    ''')

# Iberia 034
cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Arietes",
                    Tipo "Familiar",
                    Edad_minima 6,
                    Longitud_Atraccion -,
                    Altura_Minima 1.20,
                    Descripcion "La ambientación de los autos de choque que la componen, con forma de cabras y jabalíes llaman la atención a pequeños y mayores. ¡Demuestra tu pericia al volante!"
                    codigo_atraccion A23,
                    codigo_parque 03,
                    codigo_zona 034,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Jabato",
                    Tipo "Infantil",
                    Edad_minima 4,
                    Longitud_Atraccion -,
                    Altura_Minima 0.92,
                    Descripcion "La hermana pequeña de los Arietes es una atracción de autos de choque pensada para niños"
                    codigo_atraccion A24,
                    codigo_parque 03,
                    codigo_zona 034,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Tentaculus",
                    Tipo "Infantil",
                    Edad_minima 0,
                    Longitud_Atraccion -,
                    Altura_Minima 0.92,
                    Descripcion "Unas antorchas de refinado diseño sirven de vehículo individual a los niños en una atracción presidida por un aguilucho vigilante. Suben, bajan y giran con un suave balanceo"
                    codigo_atraccion A25,
                    codigo_parque 03,
                    codigo_zona 034,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Clepsidra",
                    Tipo "Infantil",
                    Edad_minima 0,
                    Longitud_Atraccion -,
                    Altura_Minima 0.92,
                    Descripcion "Unas antorchas de refinado diseño sirven de vehículo individual a los niños en una atracción presidida por un aguilucho vigilante. Suben, bajan y giran con un suave balanceo"
                    codigo_atraccion A26,
                    codigo_parque 03,
                    codigo_zona 034,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Synkopin",
                    Tipo "Infantil",
                    Edad_minima 6,
                    Longitud_Atraccion -,
                    Altura_Minima 1.10,
                    Descripcion "El hermano pequeño de la vertiginosa atracción de Terra Mítica, Synkope, adaptada a los reyes de la casa"
                    codigo_atraccion A28,
                    codigo_parque 03,
                    codigo_zona 034,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Anilus",
                    Tipo "Infantil",
                    Edad_minima 0,
                    Longitud_Atraccion -,
                    Altura_Minima 0.92,
                    Descripcion "Los niños disfrutarán de una emocionante travesía en el barco infantil de Iberia"
                    codigo_atraccion "A29",
                    codigo_parque 03,
                    codigo_zona 034,
                    ''')

# Grecia 035
cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "El laberinto del minotauro",
                    Tipo "Familiar",
                    Edad_minima 4,
                    Longitud_Atraccion -,
                    Altura_Minima 1.10,
                    Descripcion "¡Enfréntate a las mismas pruebas que Teseo y derrota al terrible Minotauro! Con la ayuda de las pistolas de luz láser, deberás derribar a las aterradoras criaturas que se esconden entre las paredes del laberinto. ¿Lograrás superar todos los obstáculos para enfrentarte cara a cara con el Minotauro?"
                    codigo_atraccion "A5",
                    codigo_parque 03,
                    codigo_zona 035,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Titanide",
                    Tipo "Emocionante",
                    Edad_minima 14,
                    Longitud_Atraccion -,
                    Altura_Minima 1.30,
                    Descripcion "Una montaña rusa invertida que alcanza la velocidad de 100 kilómetros por hora entre espectaculares giros verticales y horizontales de 360º, y vertiginosos descensos desde 31 mts de altura"
                    codigo_atraccion "A6",
                    codigo_parque 03,
                    codigo_zona 035,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Templo de Kinetos",
                    Tipo "Familiar",
                    Edad_minima 6,
                    Longitud_Atraccion -,
                    Altura_Minima 1.10,
                    Descripcion "Una gran escultura de Zeus preside el Templo de Kinetos. Adéntrate por sus pasadizos y descubre el cine 5D, una de nuestras novedades de este año. Un sistema exclusivo y vanguardista a través del cual experimentarás en primera persona sensaciones únicas jamás descritas y vivirás aventuras sin límite"
                    codigo_atraccion "A7",
                    codigo_parque 03,
                    codigo_zona 035,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Synkope",
                    Tipo "Emocionante",
                    Edad_minima 10,
                    Longitud_Atraccion -,
                    Altura_Minima 1.40,
                    Descripcion "Imagina un disco girando a 90km/h a una altura de 35m. Imagínalo balanceándose hasta formar un ángulo de 120º sobre el suelo. Ahora, imagínate en él. No eres capaz, porque no hay nada parecido. Nada te ha preparado para una sensación semejante"
                    codigo_atraccion "A8",
                    codigo_parque 03,
                    codigo_zona 035,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "La furia de Triton",
                    Tipo "Emocionante",
                    Edad_minima 6,
                    Longitud_Atraccion -,
                    Altura_Minima 0.92,
                    Descripcion "Sin duda, ésta es la atracción más buscada en los días calurosos. En su recorrido, reúne vértigo, mitología y dos refrescantes chapuzones (de 10,5 y 15 metros de altura) en una escenografía tomada de la literatura de aventuras marítimas que relataba los viajes de los antiguos cretenses y micénicos"
                    codigo_atraccion "A9",
                    codigo_parque 03,
                    codigo_zona 035,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Los Icaros",
                    Tipo "Familiar",
                    Edad_minima 6,
                    Longitud_Atraccion -,
                    Altura_Minima 1.20,
                    Descripcion "Disfruta de las vistas del parque y las playas y rascacielos de Benidorm mientras flotas suavemente en el aire. Tres filas de columpios forman la más plácida de las atracciones del Parque, situada en un lugar privilegiado"
                    codigo_atraccion "A10",
                    codigo_parque 03,
                    codigo_zona 035,
                    ''')

cursor.execute('''CREATE TABLE IF NOT EXISTS Atracciones (
                    Nombre "Alucinakis",
                    Tipo "Infantil",
                    Edad_minima 5,
                    Longitud_Atraccion -,
                    Altura_Minima 0.92,
                    Descripcion "Con esta atracción, los más pequeños también pueden sentir lo que se siente al subir a una montaña rusa de madera, al más puro estilo Magnus Colossus. Los raíles y estructura reproducen los carriles que surcaban las minas romanas y el viaje incluye dos vueltas en las que podrán disfrutar tanto niños como mayores"
                    codigo_atraccion "A11",
                    codigo_parque 03,
                    codigo_zona 035,
                    ''') """

'\ncursor.execute(\'\'\'INSERT OR IGNORE INTO Atracciones \n                   VALUES ("Tornado",\n                    "Emocionante",\n                    12,\n                    80,\n                    1.30,\n                    "¿Te atreves a desafiar una imponente torre de 80 metros de altura de la que penden sillas voladoras y que giran sin cesar a distintas alturas e intensidades?"\n                    "A13",\n                    03,\n                    032)\'\'\')\n\ncursor.execute(\'\'\'INSERT OR IGNORE INTO Atracciones \n                   VALUES ("Ayquesustus",\n                    "Infantil",\n                    5,\n                    6,\n                    0.92,\n                    "No hay excusa para que los más pequeños disfruten de una caída libre como la del Vuelo del Fénix. Sus 6 metros de altura son suficientes para causar una emoción insuperable en los niños. Además, no pueden pasar por esta atracción sin hacerse una foto aprovechando su diseño, que incluye lanzas y cascos que parecen haberse escapado de las cabezas de los pequeños guerreros"\n                    "A15",\n                    03,\n                    032) \'\'\')\n\ncursor.execute(\'\'\'INSERT OR IGNORE INTO Atracciones \n                   VALUES ("Rotundus",\n                    "Infantil",\n                    3,\n                    -,\n                    0.92,\n                    "Disfruta de las vistas a la plaza romana con esta noria infantil, ideal para toda la familia. Los vehículos con forma de pájaro elevarán suavemente a los niños por encima de la empalizada romana"\n                    "A16",\n                    03,\n                    032)\'\'\')\n\ncursor.execute(\'\'\'INSERT OR IGNORE INTO Atracciones \n                   VALUES ("Inferno",\n                    "Emocionante",\n                    14,\n                    -,\n                    1.40,\n                    "¿Te crees capaz de estar boca abajo, boca arriba, de lado, girar y sentir igual que una pelota volando a 60 km/h? ¿Eres así de lanzado? Tu te lo crees, pero nosotros no: ésta es tu oportunidad de demostrarlo. Menos hablar y más actuar..."\n                    "A17",\n                    03,\n                    032)\'\'\')\n\ncursor.execute(\'\'\'INSERT OR IGNORE INTO Atracciones \n                   VALUES ("El vuelo del Fenix",\n                    "Emocionante",\n                    10,\n                    54,\n                    1.30,\n                    "¿Estás preparado para experimentar una verdadera caída desde 54 metros de altura con una aceleración de 0.25g? en menos de 3 segundos, 100 km/h correrán por tus venas sin apenas poder respirar, lo que permite experimentar intensas sensaciones a los más osados. ¡Seguro que repites!"\n                    "A18",\n                    03,\n                    032)\'\'\')\n\n\n\n# cursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n#                     Nombre "Tornado",\n#                     Tipo "Emocionante",\n#                     Edad_minima 12,\n#                     Longitud_Atraccion 80,\n#                     Altura_Minima 1.30,\n#                     Descripcion "¿Te atreves a desafiar una imponente torre de 80 metros de altura de la que penden sillas voladoras y que giran sin cesar a distintas alturas e intensidades?"\n#                     codigo_atraccion A13,\n#                     codigo_parque 03,\n#                     codigo_zona 032,\n#                     \'\'\')\n\n# cursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n#                     Nombre "Ayquesustus",\n#                     Tipo "Infantil",\n#                     Edad_minima 5,\n#                     Longitud_Atraccion 6,\n#                     Altura_Minima 0.92,\n#                     Descripcion "No hay excusa para que los más pequeños disfruten de una caída libre como la del Vuelo del Fénix. Sus 6 metros de altura son suficientes para causar una emoción insuperable en los niños. Además, no pueden pasar por esta atracción sin hacerse una foto aprovechando su diseño, que incluye lanzas y cascos que parecen haberse escapado de las cabezas de los pequeños guerreros"\n#                     codigo_atraccion A15,\n#                     codigo_parque 03,\n#                     codigo_zona 032,\n#                     \'\'\')\n\n# cursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n#                     Nombre "Rotundus",\n#                     Tipo "Infantil",\n#                     Edad_minima 3,\n#                     Longitud_Atraccion -,\n#                     Altura_Minima 0.92,\n#                     Descripcion "Disfruta de las vistas a la plaza romana con esta noria infantil, ideal para toda la familia. Los vehículos con forma de pájaro elevarán suavemente a los niños por encima de la empalizada romana"\n#                     codigo_atraccion A16,\n#                     codigo_parque 03,\n#                     codigo_zona 032,\n#                     \'\'\')\n\n# cursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n#                     Nombre "Inferno",\n#                     Tipo "Emocionante",\n#                     Edad_minima 14,\n#                     Longitud_Atraccion -,\n#                     Altura_Minima 1.40,\n#                     Descripcion "¿Te crees capaz de estar boca abajo, boca arriba, de lado, girar y sentir igual que una pelota volando a 60 km/h? ¿Eres así de lanzado? Tu te lo crees, pero nosotros no: ésta es tu oportunidad de demostrarlo. Menos hablar y más actuar..."\n#                     codigo_atraccion A17,\n#                     codigo_parque 03,\n#                     codigo_zona 032,\n#                     \'\'\')\n\n# cursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n#                     Nombre "El vuelo del Fenix",\n#                     Tipo "Emocionante",\n#                     Edad_minima 10,\n#                     Longitud_Atraccion 54,\n#                     Altura_Minima 1.30,\n#                     Descripcion "¿Estás preparado para experimentar una verdadera caída desde 54 metros de altura con una aceleración de 0.25g? en menos de 3 segundos, 100 km/h correrán por tus venas sin apenas poder respirar, lo que permite experimentar intensas sensaciones a los más osados. ¡Seguro que repites!"\n#                     codigo_atraccion A18,\n#                     codigo_parque 03,\n#                     codigo_zona 032,\n#                     \'\'\')\n\n# Las islas 033\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Mithos",\n                    Tipo "Familiar",\n                    Edad_minima 3,\n                    Longitud_Atraccion 54,\n                    Altura_Minima 0.92,\n                    Descripcion "Un brillante carrusel que llama la atención por el día gracias a los espejos que pasean su reflejo por todas partes cuando gira y, por la noche, las bombillas de colores se encienden para dar al entorno el ambiente más alegre de Iberia"\n                    codigo_atraccion A20,\n                    codigo_parque 03,\n                    codigo_zona 033,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "La colera de Aquiles",\n                    Tipo "Emocionante",\n                    Edad_minima 14,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.20,\n                    Descripcion "Te elevas hacia el cielo mientras te balanceas a un lado y a otro, mientras giras y te inclinas hasta 120 grados. Mientras intentas saber si estás arriba o abajo, mientras decides si vas hacia la izquierda o hacia la derecha... piénsatelo mientras decides si subes o no"\n                    codigo_atraccion A21,\n                    codigo_parque 03,\n                    codigo_zona 033,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Rapidos de Argos",\n                    Tipo "Familiar",\n                    Edad_minima 0,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.20,\n                    Descripcion "Cuando aprieta el calor en el Parque sienta de maravilla un recorrido en barca siguiendo la ruta marítima en busca del Vellocino de Oro. Los viajeros, montados en una nave circular con neumáticos que los hacen rebotar y girar por todo el curso del río, se ven zarandeados por la corriente"\n                    codigo_atraccion A22,\n                    codigo_parque 03,\n                    codigo_zona 033,\n                    \'\'\')\n\n# Iberia 034\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Arietes",\n                    Tipo "Familiar",\n                    Edad_minima 6,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.20,\n                    Descripcion "La ambientación de los autos de choque que la componen, con forma de cabras y jabalíes llaman la atención a pequeños y mayores. ¡Demuestra tu pericia al volante!"\n                    codigo_atraccion A23,\n                    codigo_parque 03,\n                    codigo_zona 034,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Jabato",\n                    Tipo "Infantil",\n                    Edad_minima 4,\n                    Longitud_Atraccion -,\n                    Altura_Minima 0.92,\n                    Descripcion "La hermana pequeña de los Arietes es una atracción de autos de choque pensada para niños"\n                    codigo_atraccion A24,\n                    codigo_parque 03,\n                    codigo_zona 034,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Tentaculus",\n                    Tipo "Infantil",\n                    Edad_minima 0,\n                    Longitud_Atraccion -,\n                    Altura_Minima 0.92,\n                    Descripcion "Unas antorchas de refinado diseño sirven de vehículo individual a los niños en una atracción presidida por un aguilucho vigilante. Suben, bajan y giran con un suave balanceo"\n                    codigo_atraccion A25,\n                    codigo_parque 03,\n                    codigo_zona 034,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Clepsidra",\n                    Tipo "Infantil",\n                    Edad_minima 0,\n                    Longitud_Atraccion -,\n                    Altura_Minima 0.92,\n                    Descripcion "Unas antorchas de refinado diseño sirven de vehículo individual a los niños en una atracción presidida por un aguilucho vigilante. Suben, bajan y giran con un suave balanceo"\n                    codigo_atraccion A26,\n                    codigo_parque 03,\n                    codigo_zona 034,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Synkopin",\n                    Tipo "Infantil",\n                    Edad_minima 6,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.10,\n                    Descripcion "El hermano pequeño de la vertiginosa atracción de Terra Mítica, Synkope, adaptada a los reyes de la casa"\n                    codigo_atraccion A28,\n                    codigo_parque 03,\n                    codigo_zona 034,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Anilus",\n                    Tipo "Infantil",\n                    Edad_minima 0,\n                    Longitud_Atraccion -,\n                    Altura_Minima 0.92,\n                    Descripcion "Los niños disfrutarán de una emocionante travesía en el barco infantil de Iberia"\n                    codigo_atraccion "A29",\n                    codigo_parque 03,\n                    codigo_zona 034,\n                    \'\'\')\n\n# Grecia 035\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "El laberinto del minotauro",\n                    Tipo "Familiar",\n                    Edad_minima 4,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.10,\n                    Descripcion "¡Enfréntate a las mismas pruebas que Teseo y derrota al terrible Minotauro! Con la ayuda de las pistolas de luz láser, deberás derribar a las aterradoras criaturas que se esconden entre las paredes del laberinto. ¿Lograrás superar todos los obstáculos para enfrentarte cara a cara con el Minotauro?"\n                    codigo_atraccion "A5",\n                    codigo_parque 03,\n                    codigo_zona 035,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Titanide",\n                    Tipo "Emocionante",\n                    Edad_minima 14,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.30,\n                    Descripcion "Una montaña rusa invertida que alcanza la velocidad de 100 kilómetros por hora entre espectaculares giros verticales y horizontales de 360º, y vertiginosos descensos desde 31 mts de altura"\n                    codigo_atraccion "A6",\n                    codigo_parque 03,\n                    codigo_zona 035,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Templo de Kinetos",\n                    Tipo "Familiar",\n                    Edad_minima 6,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.10,\n                    Descripcion "Una gran escultura de Zeus preside el Templo de Kinetos. Adéntrate por sus pasadizos y descubre el cine 5D, una de nuestras novedades de este año. Un sistema exclusivo y vanguardista a través del cual experimentarás en primera persona sensaciones únicas jamás descritas y vivirás aventuras sin límite"\n                    codigo_atraccion "A7",\n                    codigo_parque 03,\n                    codigo_zona 035,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Synkope",\n                    Tipo "Emocionante",\n                    Edad_minima 10,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.40,\n                    Descripcion "Imagina un disco girando a 90km/h a una altura de 35m. Imagínalo balanceándose hasta formar un ángulo de 120º sobre el suelo. Ahora, imagínate en él. No eres capaz, porque no hay nada parecido. Nada te ha preparado para una sensación semejante"\n                    codigo_atraccion "A8",\n                    codigo_parque 03,\n                    codigo_zona 035,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "La furia de Triton",\n                    Tipo "Emocionante",\n                    Edad_minima 6,\n                    Longitud_Atraccion -,\n                    Altura_Minima 0.92,\n                    Descripcion "Sin duda, ésta es la atracción más buscada en los días calurosos. En su recorrido, reúne vértigo, mitología y dos refrescantes chapuzones (de 10,5 y 15 metros de altura) en una escenografía tomada de la literatura de aventuras marítimas que relataba los viajes de los antiguos cretenses y micénicos"\n                    codigo_atraccion "A9",\n                    codigo_parque 03,\n                    codigo_zona 035,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Los Icaros",\n                    Tipo "Familiar",\n                    Edad_minima 6,\n                    Longitud_Atraccion -,\n                    Altura_Minima 1.20,\n                    Descripcion "Disfruta de las vistas del parque y las playas y rascacielos de Benidorm mientras flotas suavemente en el aire. Tres filas de columpios forman la más plácida de las atracciones del Parque, situada en un lugar privilegiado"\n                    codigo_atraccion "A10",\n                    codigo_parque 03,\n                    codigo_zona 035,\n                    \'\'\')\n\ncursor.execute(\'\'\'CREATE TABLE IF NOT EXISTS Atracciones (\n                    Nombre "Alucinakis",\n                    Tipo "Infantil",\n                    Edad_minima 5,\n                    Longitud_Atraccion -,\n                    Altura_Minima 0.92,\n                    Descripcion "Con esta atracción, los más pequeños también pueden sentir lo que se siente al subir a una montaña rusa de madera, al más puro estilo Magnus Colossus. Los raíles y estructura reproducen los carriles que surcaban las minas romanas y el viaje incluye dos vueltas en las que podrán disfrutar tanto niños como mayores"\n                    codigo_atraccion "A11",\n                    codigo_parque 03,\n                    codigo_zona 035,\n                    \'\'\') '

In [86]:
# Aqui se insertan las dos tablas correctamente

try:
    cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                       VALUES ('Cataratas del Nilo',
                       'Emocionante',
                       6,
                       30,
                       1.20,
                       'Deslízate por una montaña rusa de agua en los sarcófagos del Faraón. A ti no te embalsamarán, pero te aseguramos que saldrás empapado de esta atracción, especialmente si te sitúas al final del vehículo. Prepárate para sentir el vértigo en sus dos caídas, la primera desde casi 20 m, y la segunda, de espaldas desde 10 m',
                       'A2',
                       '03',  -- Aquí agregué comillas simples
                       '031')''')
    conn.commit()
    print("El primer INSERT se realizó con éxito.")
except Exception as e:
    print("Ocurrió un error durante la ejecución del segundo INSERT:", e)

try:
    cursor.execute('''INSERT or Ignore INTO Atracciones 
                    VALUES ('po',
                    'pppppp',
                    7678678687,
                    'Descklñklñkcido',
                    0.92,
                    'textokfgfghfo',
                    'asdasd34',
                    '567567567',
                    '03156756756')''') 
    conn.commit()
    print("El segundo INSERT se realizó con éxito.")
except Exception as e:
    print("Ocurrió un error durante la ejecución del segundo INSERT:", e)

try:
    cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                   VALUES ('Cataratas del Nilo',
                    'Emocionante',
                    6,
                    30,
                    1.20,
                    'Deslízate por una montaña rusa de agua en los sarcófagos del Faraón. A ti no te embalsamarán, pero te aseguramos que saldrás empapado de esta atracción, especialmente si te sitúas al final del vehículo. Prepárate para sentir el vértigo en sus dos caídas, la primera desde casi 20 m, y la segunda, de espaldas desde 10 m',
                    'A2',
                    '03',
                    '031')''')


    conn.commit()
    print("El segundo INSERT se realizó con éxito.")
except Exception as e:
    print("Ocurrió un error durante la ejecución del segundo INSERT:", e)

El primer INSERT se realizó con éxito.
El segundo INSERT se realizó con éxito.
El segundo INSERT se realizó con éxito.

In [94]:
# Observamos como el codigo_atraccion da problemas si es el mismo
df = pd.read_sql_query('SELECT * FROM atracciones', conn)
df

,Nombre,Tipo,Duracion,Categoria_edad,Longitud_Atraccion,Altura_Minima,Descripcion,codigo_atraccion,codigo_parque
0,Puerto de Alejandria,Familiar,2,Desconocido,0.92,Disfruta de las vistas desde las naves Seker y...,A1,03,031
1,Cataratas del Nilo,Emocionante,6,30,1.20,Deslízate por una montaña rusa de agua en los ...,A2,03,031
2,Akuatiti,Infantil,3,Desconocido,0.92,Los más pequeños también pueden disfrutar de u...,A3,03,031
3,Infinito,Familiar,6,100,0.92,Ofrece unas vistas privilegiadas de Terra Míti...,A4,03,031

In [95]:
conn.commit()
df = pd.read_sql_query('SELECT nombre FROM Parque_atracciones ', conn)
df

          Nombre
0  Port Aventura
1        parque2
2   Terra Mitica

In [ ]:
conn.close()