In [2]:
import sqlite3
import pandas as pd

In [3]:
conn = sqlite3.connect('mi_base_de_datos.sqlite')

cursor = conn.cursor()

In [4]:
# Atracciones

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Rápidos ACME',
                    'Adolescentes y Adultos',
                    16,
                    '-',
                    110,
                    'Los Rápidos ACME son, sencillamente, ¡desternillantes! Forman una increíble atracción acuática ubicada en Cartoon Village, el lugar perfecto para tener la sensación de estar viviendo dentro de un capítulo de los alocados y traviesos Looney Tunes.',
                    'B9',
                    '02', 
                    '029')''')


cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Cataratas Salvajes',
                    'Adolescentes y Adultos',
                    16,
                    '-',
                    110,
                    'Siéntate en la primera fila (o en la última) y empápate de agua, la caída de esta atracción se produce a una gran altura, y el oleaje que provoca es simplemente espectacular.',
                    'B8',
                    '02', 
                    '028')''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Río Bravo',
                    'Todos los públicos',
                    6,
                    '-',
                    100,
                    'Río Bravo es un western que el gran Howard Hawks dirigió en 1959, con John Wayne como protagonista. Y es -también-, una de las atracciones acuáticas ineludibles de Old West Territory, en Parque Warner.',
                    'B7',
                    '02', 
                    '027')''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Correcaminos Bip Bip',
                    'Niños y Familias',
                    9,
                    '-',
                    100,
                    'Sube con tus pequeños e intenta así ayudar al incansable Wile E. Coyote en su interminable carrera para alcanzar al escurridizo Correcaminos. El velocísimo pájaro corre desenfrenadamente por el desierto de Parque Warner: ven y persíguelo con tu familia.',
                    'B6',
                    '02', 
                    '026')''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Coaster Express',
                    'Adolescentes y Adultos',
                    16,
                    '-',
                    121,
                    'Valles y cañones conforman el trazado desértico de Coaster-Express, la ‘roller coaster’ tradicional que podemos encontrar en Parque Warner Madrid.',
                    'B5',
                    '02', 
                    '025')''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Superman Atracción de Acero',
                    'Adolescentes y Adultos',
                    16,
                    '-',
                    132,
                    'Esta atracción de Parque Warner recrea la ciudad de Metrópolis, así como la entrada del famoso periódico de la urbe, el Daily Planet.',
                    'B4',
                    '02', 
                    '024')''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Batman Gotham City',
                    'Adolescentes y Adultos',
                    16,
                    '-',
                    130,
                    'La única manera de escapar de la ciudad es a través de esta montaña rusa multilaunch, única en Europa.',
                    'B3',
                    '02', 
                    '023')''')

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Lindo Gatito',
                    'Familiar',
                    6,
                    '-',
                    110,
                    '¿Te ha parecido ver a un lindo gatito? Monta entonces en esta atracción mecánica, pensada para los visitantes pequeños, para que experimenten el gusanillo de volar al tiempo que persiguen al canario más popular de la factoría Warner.',
                    'B2',
                    '02', 
                    '022')''') 

cursor.execute('''INSERT OR IGNORE INTO Atracciones 
                    VALUES ('Coyote Explosivo',
                    'Familiar',
                    9,
                    '-',
                    0.92,
                    'Wile E. Coyote, inasequible al desaliento, anda detrás del Correcaminos, 
                    y en esta ocasión ha puesto en marcha un último invento sobre el que ha depositado sus esperanzas',
                    'B1',
                    '02', 
                    '021')''')

In [6]:
cursor.execute('''INSERT OR IGNORE INTO Zonas 
                   VALUES ('023',
                    "Batman Gotham City Escape",
                    'Platos_Tipicos',
                    "La Casa de Batman",
                    "te sentirás el protagonista de tu película favorita. Seas héroe o villano, descubre todas las atracciones",
                    "12:00",
                    '1500')''')

cursor.execute('''INSERT OR IGNORE INTO Zonas 
                   VALUES ('021',
                    "Correcaminos",
                    'Platos_Tipicos',
                    "Un campo lleno de trampas a evitar",
                    "Descubre los mejores lugares para correr del coyote",
                    "10:00",
                    '300')''')

cursor.execute('''INSERT OR IGNORE INTO Zonas 
                   VALUES ('025',
                    "Old West Territory",
                    'Platos_Tipicos',
                    "Lugares del Viejo Oeste",
                    "Atrevete a ser un Vaquero montado en el caballo más veloz escapando de los apaches",
                    "10:00",
                    '6000')''')

In [8]:
cursor.execute('''INSERT OR IGNORE INTO Alojamiento 
                   VALUES ("Hotel NH Hotel Group",
                    75,
                    "4 estrellas",
                    "125 Habitaciones para familias",
                    "Hotel Moderno")''')

cursor.execute('''INSERT OR IGNORE INTO Alojamiento 
                   VALUES ("Hotel Looney Tunes",
                    55,
                    "3 estrellas",
                    "100 Habitaciones para todos los públicos",
                    "Hotel ambientado con los personajes mas característicos del mundo Warner")''')

cursor.execute('''INSERT OR IGNORE INTO Alojamiento 
                   VALUES ("Hotel Gotham",
                    120,
                    "5 estrellas",
                    "50 Habitaciones",
                    "Hotel ambientado en la casa de Bruce Wayne")''')

In [9]:
df = pd.read_sql_query('SELECT * FROM zonas ', conn)
df

,Codigo_Zona,Ambientacion,Platos_Tipicos,Espectaculos,Descripcion,Horario,Afluencia_Media
0,031,Egipcia,Platos_Tipicos,El sueño de Egipto,La vida de la joven Samira está a punto de cam...,22,Afluencia_Media
1,032,Romano,Platos_Tipicos,"Espartaco, honor y coraje",¿Quieres descubrir el origen del mito que hizo...,35,Afluencia_Media
2,033,Las islas,Platos_Tipicos,El caballo español,La pasión del elenco de bailaoras y la belleza...,8,Afluencia_Media
3,034,Ibera,Platos_Tipicos,Mitic dance,La canción que nunca pasa de moda cantada y ba...,10,Afluencia_Media
4,035,Griega,Platos_Tipicos,La magia de los dioses,El gran Zeus ha perdido su fuerza después de q...,20,Afluencia_Media
5,023,Batman Gotham City Escape,Platos_Tipicos,La Casa de Batman,te sentirás el protagonista de tu película fav...,12:00,1500
6,021,Correcaminos,Platos_Tipicos,Un campo lleno de trampas a evitar,Descubre los mejores lugares para correr del c...,10:00,300
7,025,Old West Territory,Platos_Tipicos,Lugares del Viejo Oeste,Atrevete a ser un Vaquero montado en el caball...,10:00,6000

In [10]:
conn.commit()
df = pd.read_sql_query('SELECT * FROM atracciones ', conn)
df

,Nombre,Tipo,Categoria_edad,Longitud_Atraccion,Altura_Minima,Descripcion,codigo_atraccion,codigo_parque,codigo_zona
0,Puerto de Alejandria,Familiar,2,-,0.92,Disfruta de las vistas desde las naves Seker y...,A1,3,31
1,Cataratas del Nilo,Emocionante,6,30.0,1.20,Deslízate por una montaña rusa de agua en los ...,A2,3,31
2,Akuatiti,Infantil,3,-,0.92,Los más pequeños también pueden disfrutar de u...,A3,3,31
3,Infinito,Familiar,6,100.0,0.92,Ofrece unas vistas privilegiadas de Terra Míti...,A4,3,31
4,Tornado,Emocionante,12,80.0,1.30,¿Te atreves a desafiar una imponente torre de ...,A13,3,32
5,Ayquesustus,Infantil,5,6.0,0.92,No hay excusa para que los más pequeños disfru...,A15,3,32
6,Rotundus,Infantil,3,-,0.92,Disfruta de las vistas a la plaza romana con e...,A16,3,32
7,Inferno,Emocionante,14,-,1.40,"¿Te crees capaz de estar boca abajo, boca arri...",A17,3,32
8,El vuelo del Fenix,Emocionante,10,54.0,1.30,¿Estás preparado para experimentar una verdade...,A18,3,32
9,Mithos,Familiar,3,54.0,0.92,Un brillante carrusel que llama la atención po...,A20,3,33
10,La colera de Aquiles,Emocionante,14,-,1.20,Te elevas hacia el cielo mientras te balanceas...,A21,3,33
11,Rapidos de Argos,Familiar,0,-,1.20,Cuando aprieta el calor en el Parque sienta de...,A22,3,33
12,Arietes,Familiar,6,-,1.20,La ambientación de los autos de choque que la ...,A23,3,34
13,Jabato,Infantil,4,-,0.92,La hermana pequeña de los Arietes es una atrac...,A24,3,34
14,Tentaculus,Infantil,0,-,0.92,Unas antorchas de refinado diseño sirven de ve...,A25,3,34
15,Clepsidra,Infantil,0,-,0.92,Unas antorchas de refinado diseño sirven de ve...,A26,3,34
16,Synkopin,Infantil,6,-,1.10,El hermano pequeño de la vertiginosa atracción...,A28,3,34
17,Anilus,Infantil,0,-,0.92,Los niños disfrutarán de una emocionante trave...,A29,3,34
18,El laberinto del minotauro,Familiar,4,-,1.10,¡Enfréntate a las mismas pruebas que Teseo y d...,A5,3,35
19,Titanide,Emocionante,14,-,1.30,Una montaña rusa invertida que alcanza la velo...,A6,3,35
20,Templo de Kinetos,Familiar,6,-,1.10,Una gran escultura de Zeus preside el Templo d...,A7,3,35
21,Synkope,Emocionante,10,-,1.40,Imagina un disco girando a 90km/h a una altura...,A8,3,35
22,La furia de Triton,Emocionante,6,-,0.92,"Sin duda, ésta es la atracción más buscada en ...",A9,3,35
23,Los Icaros,Familiar,6,-,1.20,Disfruta de las vistas del parque y las playas...,A10,3,35
24,Alucinakis,Infantil,5,-,0.92,"Con esta atracción, los más pequeños también p...",A11,3,35
25,Rápidos ACME,Adolescentes y Adultos,16,-,110.00,"Los Rápidos ACME son, sencillamente, ¡desterni...",B9,2,29
26,Cataratas Salvajes,Adolescentes y Adultos,16,-,110.00,Siéntate en la primera fila (o en la última) y...,B8,2,28
27,Río Bravo,Todos los públicos,6,-,100.00,Río Bravo es un western que el gran Howard Haw...,B7,2,27
28,Correcaminos Bip Bip,Niños y Familias,9,-,100.00,Sube con tus pequeños e intenta así ayudar al ...,B6,2,26
29,Coaster Express,Adolescentes y Adultos,16,-,121.00,Valles y cañones conforman el trazado desértic...,B5,2,25
30,Superman Atracción de Acero,Adolescentes y Adultos,16,-,132.00,Esta atracción de Parque Warner recrea la ciud...,B4,2,24
31,Batman Gotham City,Adolescentes y Adultos,16,-,130.00,La única manera de escapar de la ciudad es a t...,B3,2,23
32,Lindo Gatito,Familiar,6,-,110.00,¿Te ha parecido ver a un lindo gatito? Monta e...,B2,2,22
33,Coyote Explosivo,Familiar,9,-,0.92,"Wile E. Coyote, inasequible al desaliento, and...",B1,2,21

In [12]:

df = pd.read_sql_query('SELECT * FROM alojamiento', conn)
df

,Nombre,Precio,Categoria,Servicios,Ambientacion
0,Hotel NH Hotel Group,75.0,4 estrellas,125 Habitaciones para familias,Hotel Moderno
1,Hotel Looney Tunes,55.0,3 estrellas,100 Habitaciones para todos los públicos,Hotel ambientado con los personajes mas caract...
2,Hotel Gotham,120.0,5 estrellas,50 Habitaciones,Hotel ambientado en la casa de Bruce Wayne